apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 26.6.2   # версия чарта
    chart: kafka
    helm:
      releaseName: kafka
      values: |
        replicaCount: 1

        kraft:
          enabled: false   # Отключаем KRaft

        zookeeper:
          enabled: true    # Включаем Zookeeper
          replicaCount: 1

        listeners:
          client:
            protocol: PLAINTEXT
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
