apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maksim-sialitski/argocd.git
    targetRevision: HEAD
    path: app3
  destination:
    server: https://kubernetes.default.svc
    namespace: app3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
